Module3 task1
htmlacademy-javascript/1580379-keksobooking-22 pull request #4
Opened 2021-02-18 21:45 UTC by opg-x

мастер подскажи как закончить код?

2021-02-18 22:36 UTC, AlexMasterov requested changes
> мастер подскажи как закончить код?

Задание выполнено.

В этом PR нужно исправить критерии (и далее стараться их учитывать) 😃

2021-02-18 22:36 UTC, AlexMasterov commented on js/main.js
> +  const getRandomEllement = arrayName => arrayName[getRandomInteger(0, arrayName.length - 1)];
Сейчас функция `getRandomEllement` создается внутри `getRandomAdvert` при каждом её вызове, что неэффективно.

Желательно создать `getRandomEllement` отдельно, один раз, и _переиспользовать_ внутри.

2021-02-18 22:36 UTC, AlexMasterov commented on js/main.js
> +const getRandomAdvert = () => {
<details>
<summary>getRandomAdvert</summary>

https://github.com/htmlacademy-javascript/1580379-keksobooking-22/blob/d6d00fa9ac5830bc7bbb7075c4321f90ace92ad4/js/main.js#L52
https://github.com/htmlacademy-javascript/1580379-keksobooking-22/blob/d6d00fa9ac5830bc7bbb7075c4321f90ace92ad4/js/main.js#L54
</details>

[`Д 14`](https://up.htmlacademy.ru/javascript/22/criteries#d14)
> Отсутствует дублирование кода: повторяющиеся части кода переписаны как функции

Для получения массива случайной длины создай функцию:

```js
const getRandomArrayLength = (items) => { ... }
```

2021-02-18 22:36 UTC, AlexMasterov commented on js/main.js
> +new Array(10).fill(null).map(getRandomAdvert);
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-javascript/1580379-keksobooking-22/blob/d6d00fa9ac5830bc7bbb7075c4321f90ace92ad4/js/main.js#L60
</details>

Для генерации массива рекламных объявлений создай функцию:

```js
const generateAdverts = (count = 10) => { ... }
```
> Далее потребуется переиспользовать

2021-02-18 22:36 UTC, AlexMasterov commented on js/main.js
> +const CHEKS = ['12:00', '13:00', '14:00'];
CHE`K`S

[`Б 4`](https://up.htmlacademy.ru/javascript/22/criteries#b4)
> В качестве имён переменных и свойств используются _английские_ существительные

```diff
- const CHEKS = ['12:00', '13:00', '14:00'];
+ const CHECKS = ['12:00', '13:00', '14:00'];
```

2021-02-19 19:41 UTC, opg-x commented on js/main.js
> +const PHOTOS = [
+

2021-02-19 19:49 UTC, opg-x commented on js/main.js
> +  const getRandomEllement = arrayName => arrayName[getRandomInteger(0, arrayName.length - 1)];
+

2021-03-01 13:03 UTC, AlexMasterov commented
👍🏻

2021-03-01 13:03 UTC, merged